### PR TITLE
Add Sitecore 8.2 rev. 161221 (Update 2)

### PR DESCRIPTION
**Pull request by sshushliapin**
Adds Sitecore 8.2 rev. 161221 (Update 2) standalone installation. Includes:
- Sitecore images for Win 1709 and 1803.
- SQL images
- Test `docker-compose`

### CODE REVIEW

**Comment by pbering** [comment]
Looks good. Is this version something that you actively use? It's pretty old :) I was kind of hoping to not have every single older version here, but again if you have a need I will accept your PR.

**Comment by sshushliapin** [comment]
Yep, I still use it ;)

Question: I decided to go with `sitecore-base` tag name like in [9.x images](https://github.com/sitecoreops/sitecore-images/blob/09030cb85d906b01a97039bb0687a00e0847bf10/images/9.0.2%20rev.%20180604/windowsservercore-1709/sitecore-base/build.json#L2). Would it be ok if I send another PR getting rid of the `sitecore` repository in all the [existing 8.2 images](https://github.com/sitecoreops/sitecore-images/blob/09030cb85d906b01a97039bb0687a00e0847bf10/images/8.2%20rev.%20170407/windowsservercore-1709/build.json#L2)? It seems there is no need in keeping both.

**Comment by pbering** [comment]
I see that you have called the new 8.x image `sitecore-base`, this is **not** as intended when it's not a *base* image for other images (like with the 9.x images). The other *base* images are not intended to use directly but only as base for other images for a given version.

**Comment by sshushliapin** [comment]
Renamed to `sitecore`. Please take a look when you have time.

**Comment by pbering** [comment]
Thank you! Can you please rename the folder also? then we are good to go.

**Comment by sshushliapin** [comment]
Folder? Sorry, do not understand which one...

**Comment by pbering** [comment]
My fault, the folder name is correct :) I will merge now and thank you!

**Pull request merged**
